name: Executar Python via Dispatch

on:
  repository_dispatch:
    types: [run_python_job]

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Rodar script Python
        run: |
          python meu_script.py --param1 "${{ github.event.client_payload.param1 }}"
